spring:
  datasource:
#    url: jdbc:postgresql://localhost:49773/jwt_security
    url: jdbc:postgresql://localhost:64909/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
